# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_foreign_words', '0002_globalstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CWDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_word', models.CharField(max_length=100, unique=True, verbose_name='CW \u0441\u043b\u043e\u0432\u043e')),
                ('translate_word', models.CharField(max_length=255, verbose_name='\u041f\u0435\u0440\u0435\u0432\u043e\u0434 \u0441\u043b\u043e\u0432\u0430')),
            ],
            options={
                'ordering': ['foreign_word'],
                'verbose_name': 'CW \u0441\u043b\u043e\u0432\u043e',
                'verbose_name_plural': 'CW \u0441\u043b\u043e\u0432\u0430',
            },
        ),
        migrations.CreateModel(
            name='SwodeshDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_word', models.CharField(max_length=100, unique=True, verbose_name='\u0418\u043d\u043e\u0441\u0442\u0440\u0430\u043d\u043d\u043e\u0435 \u0441\u043b\u043e\u0432\u043e')),
                ('translate_word', models.CharField(max_length=255, verbose_name='\u041f\u0435\u0440\u0435\u0432\u043e\u0434 \u0441\u043b\u043e\u0432\u0430')),
            ],
            options={
                'ordering': ['foreign_word'],
                'verbose_name': '\u0418\u043d\u043e\u0441\u0442\u0440\u0430\u043d\u043d\u043e\u0435 \u0441\u043b\u043e\u0432\u043e',
                'verbose_name_plural': '\u0418\u043d\u043e\u0441\u0442\u0440\u0430\u043d\u043d\u044b\u0435 \u0441\u043b\u043e\u0432\u0430',
            },
        ),
        migrations.AddField(
            model_name='globalstatus',
            name='cw_dict_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalstatus',
            name='swodesh_dict_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='globalstatus',
            name='basic_dict_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='globalstatus',
            name='user_dict_status',
            field=models.BooleanField(default=False),
        ),
    ]
